name: Deploy CDK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: dev

jobs:
  deploy:
    uses: andrelopesmds/reusable-workflows/.github/workflows/cdk-deploy.yml@main
