name: Deploy CDK

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
        default: dev

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: TODO (Deploy)
      run: echo 'Hello world'


  trigger-next-deployment:
    name: Trigger next deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ github.event.inputs.environment }} == 'stage'
    
    steps:
    - name: Trigger Action
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/${{ github.repository }}/actions/workflows/{workflow_id}/dispatches
        workflow_id: deploy.yml
        ref: ${{ github.ref }}
        inputs: |
          environment: 'prod'
      env:
        GITHUB_TOKEN: ${{ github.token }}
