name: Test Scan Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-scan-main:
    name: Test Scan Main
    runs-on: ubuntu-latest

    steps:
    - name: TODO (Test Scan)
      run: echo 'Hello world'


  trigger-deploy-stage:
    name: Trigger deploy to stage
    runs-on: ubuntu-latest
    needs: test-scan-main

    steps:
    - name: Trigger Action
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/${{ github.repository }}/actions/workflows/{workflow_id}/dispatches
        workflow_id: deploy.yml
        ref: ${{ github.ref }}
        inputs: |
          environment: 'stage'
      env:
        GITHUB_TOKEN: ${{ github.token }}