name: Test Scan Branch

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  test-scan-branch:
    name: Test Scan Branch
    runs-on: ubuntu-latest

    steps:
      - name: TODO (Test Scan)
        run: echo 'Hello world'


  trigger-deploy-dev:
    name: Trigger deploy to dev
    runs-on: ubuntu-latest
    needs: test-scan-branch

    steps:
      name: Trigger Action
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/${{ github.repository }}/actions/workflows/{workflow_id}/dispatches
        workflow_id: deploy.yml
        ref: ${{ github.ref }}
        inputs: |
          environment: 'dev'
