name: Tests


on:
  push:
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build frontend
        run: cd frontend && yarn && REACT_APP_ENV=prod yarn build

      - name: Run Unit tests
        run: yarn test
